networks:
  backend:

volumes:
  postgis_db:
  geoserver_db:

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.27.x
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - geoserver_db:/opt/geoserver_data

  postgis:
    environment:
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    image: postgis/postgis:15-3.3
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgis_db:/var/lib/postgresql/data

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: pass
    image: dpage/pgadmin4
    networks:
      - backend
    ports:
      - 5000:80
