networks:
  backend:

volumes:
  postgis_db:

services:
  tomcat:
    image: tomcat:9-jdk11
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - ./tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/webapps:/usr/local/tomcat/webapps

  postgis:
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: pass
    image: postgis/postgis:17-3.5
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgis_db:/var/lib/postgresql/data
